{
 "title": "Smart Home",
 "tags": [ "Tasmota" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Today's Cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "price_per_kWh = 0.2664\n\nfrom(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Today\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last() \n  |> map(fn: (r) => ({ r with _value: r._value * price_per_kWh}))\n  |> group()\n  |> keep(columns: [\"_value\", \"location\"])\n  |> rename(columns: { \"_value\": \"Cost\", \"location\": \"Device\"})"
    }
   ]
  },
  {
   "title": "Today's Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Today\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last() \n  |> group()\n  |> keep(columns: [\"_value\", \"location\"])\n  |> rename(columns: { \"_value\": \"Usage\", \"location\": \"Device\"})"
    }
   ]
  },
  {
   "title": "Energy Efficiency ",
   "type": "timeseries",
   "description": "Factor value",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Factor\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "price_per_kWh = 0.2644\n\nfrom(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last() \n  |> map(fn: (r) => ({ r with _value: r._value * price_per_kWh}))\n  |> group()\n  |> keep(columns: [\"_value\", \"location\"])\n  |> rename(columns: { \"_value\": \"Cost\", \"location\": \"Device\"})"
    }
   ]
  },
  {
   "title": "Total Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> last() \n  |> group()\n  |> keep(columns: [\"_value\", \"location\"])\n  |> rename(columns: { \"_value\": \"Usage\", \"location\": \"Device\"})"
    }
   ]
  },
  {
   "title": "Voltage (V)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Voltage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Current\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Timeframe Cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "// Price per kWh\nprice_per_kWh = 0.2644\nintervals = 10.0 // seconds\n\n// Calculate the total watts per location\nwatts = from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> sum()\n\n// Calculate the count of data points per location\ncounts = from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> count()\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) }))\n  |> keep(columns: [\"_value\"])\n  \n// Merge watts and counts data\nmerged = union(tables: [watts, counts])\n\n// Add a \"tag\" to identify which stream the value belongs to\nmerged_with_tags = merged\n  |> map(fn: (r) => ({\n    r with\n    stream: if exists r[\"_measurement\"] and r[\"_measurement\"] == \"Power\" then \"watts\" else \"counts\"\n  }))\n\n// Now compute the cost using watts and counts, grouped by location\nresult = merged_with_tags\n  |> group(columns: [\"location\", \"stream\"])  // Group by location and stream (watts or counts)\n  |> map(fn: (r) => ({\n    location: r.location,\n    stream: r.stream,\n    _value: if r.stream == \"watts\" then r._value else 0.0\n  }))\n  |> sum()  // Sum all the values for watts and counts\n  |> map(fn: (r) => ({\n    location: r.location,\n    stream: r.stream,\n    _value: (r._value / 1000.0) * intervals / 3600.0 * price_per_kWh\n  }))\n\nfiltered = result\n  |> filter(fn: (r) => r.stream == \"watts\")\n  |> group()\n  |> rename(columns: {\"_value\": \"Cost\", \"location\": \"Device\"})\n  |> keep(columns: [\"Cost\", \"Device\"])\n  |> yield(name: \"cost\")\n"
    }
   ]
  },
  {
   "title": "Timeframe Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "// Price per kWh\nintervals = 10.0 // seconds\n\n// Calculate the total watts per location\nwatts = from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> sum()\n\n// Calculate the count of data points per location\ncounts = from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Power\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> count()\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) }))\n  |> keep(columns: [\"_value\"])\n  \n// Merge watts and counts data\nmerged = union(tables: [watts, counts])\n\n// Add a \"tag\" to identify which stream the value belongs to\nmerged_with_tags = merged\n  |> map(fn: (r) => ({\n    r with\n    stream: if exists r[\"_measurement\"] and r[\"_measurement\"] == \"Power\" then \"watts\" else \"counts\"\n  }))\n\n// Now compute the cost using watts and counts, grouped by location\nresult = merged_with_tags\n  |> group(columns: [\"location\", \"stream\"])  // Group by location and stream (watts or counts)\n  |> map(fn: (r) => ({\n    location: r.location,\n    stream: r.stream,\n    _value: if r.stream == \"watts\" then r._value else 0.0\n  }))\n  |> sum()  // Sum all the values for watts and counts\n  |> map(fn: (r) => ({\n    location: r.location,\n    stream: r.stream,\n    _value: (r._value / 1000.0) * intervals / 3600.0 \n  }))\n\nfiltered = result\n  |> filter(fn: (r) => r.stream == \"watts\")\n  |> group()\n  |> rename(columns: {\"_value\": \"Usage\", \"location\": \"Device\"})\n  |> keep(columns: [\"Usage\", \"Device\"])\n  |> yield(name: \"usage\")\n"
    }
   ]
  },
  {
   "title": "Apparent Power (Voltage Ampere)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "query": "from(bucket: \"smart_home\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ApparentPower\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}