# -*- coding: utf-8 -*-
# Copyright (C) 2025 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#
# Workflow to build the docker image.

name: Build Docker Image

on:
  workflow_call:

permissions:
  contents: read

jobs:
  Build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit
          disable-sudo: true

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build and push Docker image
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          file: Dockerfile
          push: false
          tags: btschwertfeger/mqtt-bridge:latest
